trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: dotnet restore
  displayName: 'Restore NuGet packages'

- script: dotnet build --configuration Release
  displayName: 'Build'

- script: dotnet test --configuration Release --logger trx --collect:"XPlat Code Coverage"
  displayName: 'Run Tests'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'VSTest'
    testResultsFiles: '**/*.trx'
    failTaskOnFailedTests: true
  displayName: 'Publish Test Results'
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)'
    ArtifactName: 'MyArtifact'
