trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: dotnet restore
  displayName: 'Restore NuGet packages'

- script: dotnet build --configuration Release
  displayName: 'Build'

- script: dotnet test --configuration Release --logger trx --collect:"XPlat Code Coverage"
  displayName: 'Run Tests'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'VSTest'
    testResultsFiles: '**/*.trx'
    failTaskOnFailedTests: true
  displayName: 'Publish Test Results'

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'cobertura'
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.cobertura.xml'
    reportDirectory: '$(System.DefaultWorkingDirectory)/**'
    failIfCoverageEmpty: true
  displayName: 'Publish Code Coverage Results'
